name: CI/CD

on:
  push:
    paths-ignore:
      - README.md
    branches: [master]
    tags: [v*.*.*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Build
        uses: docker://rust:1.52.1@sha256:5f3bbf6200c057c4934deac814224e0038baa018c76aa54dfb84dd734315dad4
        with:
          args: /bin/sh -c "cargo test && cargo build --release"
      - name: Create a Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ''
          draft: false
      - name: Upload a Release Asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/base
          asset_name: base-linux-amd64
          asset_content_type: application/octet-stream
